
name: bd-sca-security-scan-action
on:
  push:
    branches: [ main, master, develop, stage, release ] 
  pull_request:
    branches: [ main, master, develop, stage, release ] 
  workflow_dispatch:
jobs:  
  blackduck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Maven Build
      run: mvn -B -DskipTests pacakage
    - name: Black Duck SCA Scan
      uses: blackduck-inc/black-duck-security-scan@v2.1.1
      env:
        DETECT_PROJECT_NAME: daniel-action-test
        DETECT_PROJECT_VERSION_NAME: main
      with:
        blackducksca_url: ${{ secrets.BLACKDUCKSCA_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
        blackducksca_prComment_enabled: true
        blackducksca_fixpr_enabled: true
        mark_build_status: success
        github_token: ${{ secrets.GITHUB_TOKEN }}
