
name: bd-sca-security-scan-action
on:
  push:
    branches: [ main, master, develop, stage, release ] 
  pull_request:
    branches: [ main, master, develop, stage, release ] 
  workflow_dispatch:
jobs:  
  blackduck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Get event_name
      run: echo event type ${{github.event_name}}
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Install libraries
      run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    - name: Maven Build
      run: mvn -B -DskipTests package
    - name: Black Duck SCA Scan
      id: black-duck-full-scan
      if: ${{ github.event_name != 'pull_request' }}
      uses: blackduck-inc/black-duck-security-scan@v2.1.1
      env:
        DETECT_PROJECT_NAME: daniel-action-test-v2
        DETECT_PROJECT_VERSION_NAME: main
        DETECT_EXCLUDED_DETECTOR_TYPES: GIT
        BLACKDUCK_TRUST_CERT: true
      with:
        blackducksca_url: ${{ secrets.BLACKDUCKSCA_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
        blackducksca_scan_failure_severities: BLOCKER,CRITICAL,MAJOR
        blackducksca_prComment_enabled: true
        blackducksca_fixpr_enabled: true
        mark_build_status: success
        github_token: ${{ secrets.GITHUB_TOKEN }}
        blackducksca_scan_full: false
        detect_search_depth: 10



