# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build:
      runs-on: [ ubuntu-latest ]
      steps:
        - name: Checkout Source
          uses: actions/checkout@v4
        - name: Blackduck Scan
  # You may pin to the exact commit or the version.
  
 
          uses: blackduck-inc/black-duck-security-scan@v2.1.1
          ### Use below configuration to set specific detect environment variables
          env:
           DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          with:
            blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
            # API token to access blackduck
            blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
            # Directory to find or install detect
            #detect_install_directory: # optional
            # Scan Mode. (true for intelligent scan & false for rapid scan)
            blackducksca_scan_full: true
            
